# See https://pre-commit.com for more information
# Install: pip install pre-commit && pre-commit install
repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: system
        types: [javascript]
        pass_filenames: true

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
